elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
      - "9200:9200"

logstash:
    build: logstash/
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
        - "5000:5000"
        - "5514:5514"
    links:
        - elasticsearch

kibana:
    build: kibana/
    ports:
        - "5601"
    links:
        - elasticsearch
    hostname: kibana.local
    environment:
        - "INTERLOCK_DATA={\"port\": 5601, \"hostname\":\"kibana\", \"domain\": \"demo\"}"
