elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
      - "9200:9200"

logstash:
    image: logstash:latest
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
        - ./logstash/config:/etc/logstash/conf.d
    ports:
        - "5000:5000"
        - "5514:5514"
    links:
        - elasticsearch

kibana:
    build: kibana/
    volumes:
        - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
    ports:
        - "5601"
    links:
        - elasticsearch
    hostname: kibana.local
    environment:
        - "INTERLOCK_DATA={\"port\": 5601}"

lb:
    image: ehazlett/interlock:latest
    command: -D -p haproxy start
    environment:
        HAPROXY_PROXY_BACKEND_OVERRIDE_ADDRESS: 192.168.7.66
    volumes:
        - /tmp/swarm.sock:/var/run/docker.sock
    links:
        - kibana
    ports:
        - "80:80"
